server:
  port: 8080

spring:
  application:
    name: ChatBot

  datasource:
    url: jdbc:mysql://localhost:3306/chatbot_db?useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

  # ===== Google Gemini AI =====
  ai:
    google:
      genai:
          api-key: ${GEMINI_API_KEY}
          chat:
            options:
              model: gemini-3-flash-preview
              temperature: 0.7
              maxOutputTokens: 1000

logging:
  level:
    org.springframework.web: INFO
    com.sujan: DEBUG

# ===== Swagger / OpenAPI =====
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    try-it-out-enabled: true
    operations-sorter: method
    tags-sorter: alpha
    display-request-duration: true